#!/bin/bash
set -e

VIP=$1
PASS=$2
GW=$3
NET=$4

DEV=eth1

if [ -z "$PASS" ]
then
  echo "$0 virtual-ip password"
  exit 1
fi

# Check is haproxy.cfg is valid before we start ucarp
haproxy -c -f /haproxy/haproxy.cfg

echo "Waiting for external interface"
pipework --wait -i $DEV

if [ -n "$GW" ]
then
  OLDGW=`ip route |awk '/^default/ {print $3}'`
  echo "Moving default route $OLDGW->$GW"
  ip route del default
  ip route add default via $GW

  if [ -n "$NET" ]
  then
    echo "Add route $NET to old gateway $OLDGW"
    ip route add $NET via $OLDGW
  fi
fi

[ -z "$VHID" ] && VHID=`IFS=.;set -- $VIP; echo $(( ($1+$2+$3+$4) % 255 ))`
echo "Using id: $VHID"

NET=`ip addr show dev $DEV|awk '/inet[^6]/ {print $2}'`
RIP=`echo $NET|cut -d/ -f1`

ucarp -i $DEV -s $RIP -v $VHID -p $PASS -a $VIP \
      -u ./scripts/up -d ./scripts/down -z &

PID=$!

haproxy -f /haproxy/haproxy.cfg

kill $PID
sleep 5
kill -9 $PID
