#!/bin/bash
set -e
trap "shutdown" SIGINT SIGTERM

shutdown() {
  [ -z "$PID" ] && exit 0
  kill -USR2 $PID # demote
  sleep 1
  kill $PID       # kill gracefully so it can unbound IP
  sleep 1
  kill -9 $PID
  exit 0
}

export VIP=$1
export PASS=$2
export GW=$3
export NET=$4
export DEV=eth1

if [ -z "$PASS" ]
then
  echo "$0 virtual-ip password"
  exit 1
fi

# Generate keys if not provided
[ -f dhparam.pem ] ||
      openssl dhparam -out dhparam.pem 2048
[ -f server-key.pem ] ||
      openssl genrsa -out server-key.pem 2048
[ -f server-csr.pem ] ||
      openssl req -new -key server-key.pem -out server-csr.pem -subj /CN=*/
[ -f server-cert.pem ] ||
      openssl x509 -req -in server-csr.pem -out server-cert.pem -signkey server-key.pem -days 3650

# Check is haproxy.cfg is valid before we start ucarp
haproxy -c -f /haproxy/haproxy.cfg
nginx -t -c /haproxy/nginx.conf

echo "Waiting for external interface"
pipework --wait -i $DEV

/haproxy/scripts/ucarp &
PID=$!

/usr/sbin/nginx   -c /haproxy/nginx.conf  || shutdown &
/usr/sbin/haproxy -f /haproxy/haproxy.cfg || shutdown
